### PR TITLE
Linting the project, closes #101

### LINKED ISSUE #101: Lint the Project
- [x] Research about linters for PHP & Laravel
- [x] Configure the exceptions
- [x] Push lint config to source code for others to use for uniformity

### PR DESCRIPTION
**Pull request by kapilace6**
* PHPCS & PHPCBF included into the project dev dependencies
* Custom Ruleset for project included

### CODE REVIEW

File: app/Driver.php [hunk 1]
```diff
@@ -4,38 +4,43 @@
...
+    private const DELIMITER = '~$~';
+    public static function getAliases()
+    {
         $alias_list = Driver::pluck('alias');
 
-        foreach($alias_list as $i => $alias) {
+        foreach ($alias_list as $i => $alias) {
             $arr = array();
-            $arr = explode(self::delimiter, $alias);
+            $arr = explode(self::DELIMITER, $alias);
```
Comment (TheFreeman15) [inline app/Driver.php:23]: Is this thing case sensitive or no ?

Comment (kapilace6) [reply app/Driver.php:23]: All references were changed to uppercase. PSR12 mentions that as the standard for constants.
